#!/usr/bin/env bash
# Configures a new ubuntu machine to below requirement (this script will be run on the server itself):
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a Get request (requesting a page) using curl, it must return a page that contains the string Hello World!

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
if ["$(pgrep -x 'nginx' | wc -l)" -ge 1 ]
then
	service nginx restart
else
	service nginx start
fi
