#!/usr/bin/env bash
# Configures a new ubuntu machine to below requirement (this script will be run on the server itself):
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a Get request (requesting a page) using curl, it must return a page that contains the string Hello World!

sudo apt update
sudo apt install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
