#!/usr/bin/env bash
# Return a list of all currently running processes.
#+ Must Shows all processes, for all users, including those which might not have a TTY
#+ Display a user-oriented format
#+ Show process hierarchy.

ps -axuf
