#!/usr/bin/env bash
# Displays "To infinity and beyond" but prints "I am invincible!!!" for SIGTERM signal.
trap "echo I am invincible!!!" SIGTERM
while true
do
echo "To infinity an beyond"
sleep 2
done
